name: Mazra3ty

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  
  farmer:
    build:
      context: ./farmer
    ports:
      - "5174:5174"
    volumes:
      - ./farmer:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    environment:
      - mongodb+srv://AbdelrahmanAbdelrassoul:HdPyluW8xxuCig5h@mazra3tydb.btckw.mongodb.net/?retryWrites=true&w=majority&appName=Mazra3tyDB
      - PORT=5000
    volumes:
    - ./backend:/app
  
